"""Structured provider/supplier archetype profiles.

Each archetype is scored 1-5 (low-high) across the behavioral dimensions called out in the
original simulation brief, so downstream LLM calls reason from a grounded profile instead of
just a name. `notes` captures qualitative context that doesn't reduce to a 1-5 score.
"""

ARCHETYPES = [
    {
        "name": "Legitimate high-volume DME supplier",
        "financial_pressure": 2,
        "risk_tolerance": 2,
        "medicare_dependence": 3,
        "compliance_sophistication": 4,
        "coding_sophistication": 4,
        "access_to_beneficiaries": 4,
        "referral_relationships": 3,
        "geographic_reach": 4,
        "willingness_to_exploit_ambiguity": 2,
        "volume_growth_objective": 3,
        "audit_awareness": 4,
        "coordination_with_others": 2,
        "notes": "Established, diversified payer mix, mature billing systems. Baseline/control-like "
                 "but scale means even small error rates create material dollars.",
    },
    {
        "name": "Small independent DME supplier under financial pressure",
        "financial_pressure": 5,
        "risk_tolerance": 4,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 2,
        "access_to_beneficiaries": 2,
        "referral_relationships": 2,
        "geographic_reach": 1,
        "willingness_to_exploit_ambiguity": 4,
        "volume_growth_objective": 3,
        "audit_awareness": 2,
        "coordination_with_others": 1,
        "notes": "Cash-flow driven, thin compliance staffing, may drift into abuse opportunistically "
                 "under cash pressure rather than by design.",
    },
    {
        "name": "Rapidly growing DME supplier",
        "financial_pressure": 3,
        "risk_tolerance": 4,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 4,
        "referral_relationships": 4,
        "geographic_reach": 3,
        "willingness_to_exploit_ambiguity": 4,
        "volume_growth_objective": 5,
        "audit_awareness": 2,
        "coordination_with_others": 3,
        "notes": "Growth targets outpace compliance build-out; classic profile for aggressive volume "
                 "acquisition (marketing/lead-gen spend, new-beneficiary surges) preceding scrutiny.",
    },
    {
        "name": "Telehealth-linked DME supplier",
        "financial_pressure": 3,
        "risk_tolerance": 4,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 5,
        "referral_relationships": 5,
        "geographic_reach": 5,
        "willingness_to_exploit_ambiguity": 4,
        "volume_growth_objective": 5,
        "audit_awareness": 2,
        "coordination_with_others": 4,
        "notes": "Order-generation decoupled from physical exam; high beneficiary reach via call "
                 "centers; well-documented historical fraud pattern (braces/genetic-test analogues).",
    },
    {
        "name": "DME supplier heavily dependent on lead-generation companies",
        "financial_pressure": 3,
        "risk_tolerance": 4,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 2,
        "access_to_beneficiaries": 5,
        "referral_relationships": 5,
        "geographic_reach": 5,
        "willingness_to_exploit_ambiguity": 4,
        "volume_growth_objective": 5,
        "audit_awareness": 2,
        "coordination_with_others": 5,
        "notes": "Beneficiary acquisition outsourced to third-party marketers; weak control over how "
                 "leads/orders were generated; high coordination risk (kickback-adjacent structures).",
    },
    {
        "name": "Supplier with unusually high Medicare concentration",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 5,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 2,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 3,
        "audit_awareness": 3,
        "coordination_with_others": 2,
        "notes": "No commercial-payer cross-check on billing patterns; Medicare rules are the entire "
                 "revenue model, raising incentive to fully exploit every allowable rule.",
    },
    {
        "name": "Multi-state supplier",
        "financial_pressure": 2,
        "risk_tolerance": 3,
        "medicare_dependence": 3,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 5,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 3,
        "audit_awareness": 3,
        "coordination_with_others": 2,
        "notes": "Can route claims through the MAC jurisdiction/state with the most favorable "
                 "enforcement posture or LCD interpretation; enables jurisdiction arbitrage.",
    },
    {
        "name": "Physician practice dispensing or ordering DME",
        "financial_pressure": 2,
        "risk_tolerance": 3,
        "medicare_dependence": 2,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 5,
        "referral_relationships": 5,
        "geographic_reach": 2,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 2,
        "audit_awareness": 3,
        "coordination_with_others": 3,
        "notes": "Controls both the order and the documentation that justifies it (self-referral "
                 "dynamic); can shape medical necessity narrative to fit desired equipment.",
    },
    {
        "name": "Home health-associated provider/supplier",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 4,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 4,
        "referral_relationships": 4,
        "geographic_reach": 2,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 3,
        "audit_awareness": 3,
        "coordination_with_others": 4,
        "notes": "Sits at a care-setting boundary where DME bundling/consolidated-billing rules "
                 "interact with home health episodes; timing of orders around episode windows matters.",
    },
    {
        "name": "Skilled nursing facility-associated provider/supplier",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 4,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 4,
        "referral_relationships": 4,
        "geographic_reach": 1,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 2,
        "audit_awareness": 3,
        "coordination_with_others": 4,
        "notes": "SNF consolidated billing / Part A vs Part B boundaries create timing-sensitive "
                 "opportunities around admission/discharge dates.",
    },
    {
        "name": "Orthotics/prosthetics supplier",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 3,
        "compliance_sophistication": 3,
        "coding_sophistication": 4,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 2,
        "willingness_to_exploit_ambiguity": 4,
        "willingness_to_exploit_ambiguity_note": "L-code complexity creates wide coding discretion",
        "volume_growth_objective": 3,
        "audit_awareness": 3,
        "coordination_with_others": 2,
        "notes": "High HCPCS (L-code) complexity and customization language ('custom fabricated' vs "
                 "'custom fitted') creates wide, defensible-sounding coding discretion.",
    },
    {
        "name": "Oxygen/respiratory equipment supplier",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 4,
        "compliance_sophistication": 3,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 4,
        "referral_relationships": 3,
        "geographic_reach": 3,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 3,
        "audit_awareness": 3,
        "coordination_with_others": 2,
        "notes": "Capped rental and recertification (oximetry retest) rules create recurring, "
                 "date-driven billing events well suited to systematic exploitation.",
    },
    {
        "name": "Enteral/parenteral nutrition supplier",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 3,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 3,
        "audit_awareness": 2,
        "coordination_with_others": 2,
        "notes": "Recurring-supply refill model (like CGM/incontinence supplies) is the classic "
                 "auto-ship-without-contact abuse vector.",
    },
    {
        "name": "Supplier specializing in recurring supplies or accessories",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 4,
        "compliance_sophistication": 2,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 4,
        "referral_relationships": 3,
        "geographic_reach": 4,
        "willingness_to_exploit_ambiguity": 4,
        "volume_growth_objective": 4,
        "audit_awareness": 2,
        "coordination_with_others": 3,
        "notes": "Business model is refill cadence itself; every refill-interval or 'ran out early' "
                 "rule is directly monetizable at scale.",
    },
    {
        "name": "Supplier using aggressive coding/revenue-cycle consultants",
        "financial_pressure": 2,
        "risk_tolerance": 4,
        "medicare_dependence": 3,
        "compliance_sophistication": 4,
        "coding_sophistication": 5,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 3,
        "willingness_to_exploit_ambiguity": 5,
        "volume_growth_objective": 4,
        "audit_awareness": 4,
        "coordination_with_others": 2,
        "notes": "High technical sophistication paired with high willingness to push interpretation - "
                 "the most likely archetype to find genuinely novel rule collisions and defend them as "
                 "'compliant.' High audit awareness means it also adapts fastest after edits/denials.",
    },
    {
        "name": "Organized fraud-ring archetype (cooperating suppliers, clinicians, marketers, beneficiaries)",
        "financial_pressure": 4,
        "risk_tolerance": 5,
        "medicare_dependence": 5,
        "compliance_sophistication": 1,
        "coding_sophistication": 3,
        "access_to_beneficiaries": 5,
        "referral_relationships": 5,
        "geographic_reach": 4,
        "willingness_to_exploit_ambiguity": 5,
        "volume_growth_objective": 5,
        "audit_awareness": 3,
        "coordination_with_others": 5,
        "notes": "Intentional, coordinated criminal enterprise; expected to churn shell suppliers, "
                 "rotate NPIs/beneficiaries, and move geographically once detected.",
    },
    {
        "name": "Opportunistic individual provider (no initial fraud intent, responds to incentives)",
        "financial_pressure": 3,
        "risk_tolerance": 3,
        "medicare_dependence": 3,
        "compliance_sophistication": 2,
        "coding_sophistication": 2,
        "access_to_beneficiaries": 3,
        "referral_relationships": 2,
        "geographic_reach": 1,
        "willingness_to_exploit_ambiguity": 3,
        "volume_growth_objective": 2,
        "audit_awareness": 2,
        "coordination_with_others": 1,
        "notes": "Represents drift/normalization risk: starts compliant, observes ambiguous rules "
                 "being billed aggressively by peers without consequence, and gradually adopts the "
                 "same pattern. Important because it's the most common real-world path into abuse.",
    },
    {
        "name": "Compliance-oriented supplier (control group)",
        "financial_pressure": 2,
        "risk_tolerance": 1,
        "medicare_dependence": 3,
        "compliance_sophistication": 5,
        "coding_sophistication": 4,
        "access_to_beneficiaries": 3,
        "referral_relationships": 3,
        "geographic_reach": 3,
        "willingness_to_exploit_ambiguity": 1,
        "volume_growth_objective": 2,
        "audit_awareness": 5,
        "coordination_with_others": 1,
        "notes": "Baseline for false-positive calibration: exhibits legitimate reasons for patterns "
                 "that might otherwise look suspicious (e.g. genuinely complex patient mix).",
    },
]

ARCHETYPE_NAMES = [a["name"] for a in ARCHETYPES]

COLLISION_CATEGORIES = {
    "A": "Rule collisions - two individually valid CMS rules interact to create an unintended opportunity",
    "B": "Temporal exploitation - timing, replacement intervals, rental periods, refills, eligibility transitions",
    "C": "Entity arbitrage - behavior differs depending on billing entity (supplier/physician/hospital/SNF/HHA)",
    "D": "Code-path arbitrage - economically similar items follow different HCPCS/modifier/rental/purchase paths",
    "E": "Distributed behavior - normal at single NPI, suspicious as a network",
    "F": "Low-and-slow behavior - stays below simple thresholds but anomalous longitudinally",
    "G": "Adaptive behavior - how suppliers shift tactics after denials/edits/audits/policy changes",
    "H": "Archetype differences - which vulnerabilities are most attractive to which archetypes",
}
